// <auto-generated />
namespace POPpicService.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class DurationFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DurationFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201406120636132_DurationFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
